---
- name: Copy .bashrc
  copy:
      src: "{{ role_path }}/files/.bashrc"
      dest: ~/.bashrc
- name: Install git
  apt:
      name: git
- name: Install sudo
  apt:
      name: sudo
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
- name: Fix broken packages
  ansible.builtin.shell: apt --fix-broken install
  become: yes
- name: Install apt-fast
  shell: |
      /bin/bash -c "$(curl -sL https://git.io/vokNn)"
      alias apt-get='apt-fast'
      touch ~/.bash_aliases
      echo "alias apt-get='apt-fast'" >> ~/.bash_aliases
  run_once: true
- name: Install building tools
  apt:
      name:
          - build-essential
          - gcc
          - g++
          - clang
          - llvm
          - make
          - automake
          - autoconf
          - cmake
      # state: latest
      state: present
      # update_cache: yes
- name: Install compress and uncompress tools
  apt:
      name:
          - zip
          - unzip
      state: present
  become: yes
- name: Install silversearcher-ag
  apt:
      name: silversearcher-ag
  become: yes
- name: Install ctags, cscope
  apt:
      name:
          - ctags
          - cscope
      state: present
  become: yes
