---
- name: Copy .bashrc
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: ~/.bashrc
- name: Install apt-fast
  shell: |
    /bin/bash -c "$(curl -sL https://git.io/vokNn)"
    alias apt-get='apt-fast'
    touch ~/.bash_aliases
    echo "alias apt-get='apt-fast'" >> ~/.bash_aliases
  run_once: true
- name: Install building tools
  apt:
    name: "{{ item }}"
    # state: latest
    state: present
  # update_cache: yes
  with_items:
    - build-essential
    - gcc
    - g++
    - clang
    - llvm
    - make
    - automake
    - autoconf
    - cmake
- name: Install compress and uncompress tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
- name: Install silversearcher-ag
  apt:
    name: silversearcher-ag
- name: Install ctags, cscope
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ctags
    - cscope
